
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_matmul_perso.ipynb

from exp.nb_00 import *
import operator
from torch import allclose

def test(a,b,cmp, cname='None'):
    if cname is None: cname=cmp.__name__
    assert cmp(a,b), f"{cname}:\n{a}\n{b}"


def test_eq(a,b): return test(a,b,operator.eq, "==")

def near(a,b): return allclose(a,b, rtol=1e-3, atol=1e-5)

def test_near(a,b): return test(a,b,near,'near')

from pathlib import Path
from IPython.core.debugger import set_trace
from fastai import datasets
import pickle, gzip, math, torch, matplotlib as mpl
import matplotlib.pyplot as plt
from torch import tensor

MNIST_URL='http://deeplearning.net/data/mnist/mnist.pkl'